default: &default
  adapter: postgresql
  pool: 20
  timeout: 5000
  host: localhost
  user: root

development:
  <<: *default
  database: invoice_tracker
  password: root

# test:
#   <<: *default
#   database: aranjewels_test

# production:
#   <<: *default
#   database: aranjewels_production
